package lt.vu.usecases.mybatis.dao;

import lt.vu.usecases.mybatis.model.Company;
import org.mybatis.cdi.Mapper;
import java.util.List;

@Mapper
public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    Company selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    List<Company> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPANY
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    int updateByPrimaryKey(Company record);
}