package lt.vu.usecases.mybatis.dao;

import lt.vu.usecases.mybatis.model.Deed;

import java.util.List;

public interface DeedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEED
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEED
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    int insert(Deed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEED
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    Deed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEED
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    List<Deed> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.DEED
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    int updateByPrimaryKey(Deed record);
}