package lt.vu.usecases.mybatis.dao;

import lt.vu.usecases.mybatis.model.Deed;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface DeedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    int insert(Deed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    Deed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    List<Deed> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COURSE
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    int updateByPrimaryKey(Deed record);
}