package lt.vu.usecases.mybatis.model;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPANY.ID
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPANY.TITLE
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPANY.ID
     *
     * @return the value of PUBLIC.COMPANY.ID
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPANY.ID
     *
     * @param id the value for PUBLIC.COMPANY.ID
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPANY.TITLE
     *
     * @return the value of PUBLIC.COMPANY.TITLE
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPANY.TITLE
     *
     * @param title the value for PUBLIC.COMPANY.TITLE
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }
}