package lt.vu.usecases.mybatis.model;

public class Deed {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DEED.ID
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DEED.NAME
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DEED.ID
     *
     * @return the value of PUBLIC.DEED.ID
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DEED.ID
     *
     * @param id the value for PUBLIC.DEED.ID
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DEED.NAME
     *
     * @return the value of PUBLIC.DEED.NAME
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DEED.NAME
     *
     * @param name the value for PUBLIC.DEED.NAME
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}