package lt.vu.usecases.mybatis.model;

public class EmployeeDeed {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE_DEED.EMPLOYEE_ID
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EMPLOYEE_DEED.DEED_ID
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    private Integer deedId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE_DEED.EMPLOYEE_ID
     *
     * @return the value of PUBLIC.EMPLOYEE_DEED.EMPLOYEE_ID
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE_DEED.EMPLOYEE_ID
     *
     * @param employeeId the value for PUBLIC.EMPLOYEE_DEED.EMPLOYEE_ID
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EMPLOYEE_DEED.DEED_ID
     *
     * @return the value of PUBLIC.EMPLOYEE_DEED.DEED_ID
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    public Integer getDeedId() {
        return deedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EMPLOYEE_DEED.DEED_ID
     *
     * @param deedId the value for PUBLIC.EMPLOYEE_DEED.DEED_ID
     *
     * @mbg.generated Mon May 06 19:02:24 EEST 2019
     */
    public void setDeedId(Integer deedId) {
        this.deedId = deedId;
    }
}