package lt.vu.usecases.mybatis.model;

public class EmployeeDeed {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_COURSE.STUDENT_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_COURSE.COURSE_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    private Integer deedId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_COURSE.STUDENT_ID
     *
     * @return the value of PUBLIC.STUDENT_COURSE.STUDENT_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_COURSE.STUDENT_ID
     *
     * @param employeeId the value for PUBLIC.STUDENT_COURSE.STUDENT_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_COURSE.COURSE_ID
     *
     * @return the value of PUBLIC.STUDENT_COURSE.COURSE_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public Integer getDeedId() {
        return deedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_COURSE.COURSE_ID
     *
     * @param deedId the value for PUBLIC.STUDENT_COURSE.COURSE_ID
     *
     * @mbg.generated Tue Mar 14 20:35:20 EET 2017
     */
    public void setDeedId(Integer deedId) {
        this.deedId = deedId;
    }
}